[package]
name = "rego"
version = "0.1.0"
authors = ["Mike Yagley <myagley@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.18"
ordered-float = "1"
serde = "1"
tracing = "0.1"
typed-arena = "2"

[build-dependencies]
lalrpop = "0.18"

[dev-dependencies]
tracing-subscriber = "0.2"
